@startuml PlcController

class PlcController {
  + StartConnecting() : void
  + IsConnected() : bool
  + EnableSystemCheck() : void
  + StartSafety() : void
  + RestartEStops() : void
  + AbortRobot() : void
  + StartRobot() : void
  __
  <i><color:Gray>PLC safety system client</color></i>
  <i><color:Gray>Port: 10002</color></i>
}

@enduml
