@startuml system_states_example

skinparam {
  ranksep 100
  nodesep 100
}

[*] --> PLC_Init
state PLC_events_ADD <<choice>>
PLC_Init -down-> PLC_events_ADD : Safety
PLC_Init -down-> PLC_events_ADD : Connected
PLC_events_ADD -down-> Mobile_Platform_Init

state Robot_Init_events_ADD <<choice>>
Mobile_Platform_Init -down-> Robot_Init_events_ADD : Safety
Mobile_Platform_Init -down-> Robot_Init_events_ADD : Connected
Robot_Init_events_ADD -down-> Robot_Init

PLC_Error : Popup message
PLC_Error: Turn on Leds
PLC_Init -left-> PLC_Error : Cannot_Connect OR Not_Safety
PLC_Error -right-> PLC_Init : User_restart
PLC_Error -left-> [*] : User_manual

Mobile_Platform_Init -up-> PLC_Init : Disconnected
Mobile_Platform_Init -right-> Mobile_Platform_Conn_Failed : Status_failed OR Command_failed

Mobile_Platform_Conn_Failed : Popup message
Mobile_Platform_Conn_Failed: Turn on Leds
Mobile_Platform_Conn_Failed -left-> Mobile_Platform_Init : User_action

Mobile_Platform_Init -left-> PLC_Disconnect : PLC_conn_failed

PLC_Disconnect : Popup message
PLC_Disconnect: Turn on Leds
PLC_Disconnect -left-> PLC_Reconnection : User_action
PLC_Reconnection -right-> PLC_Disconnect : Reconn_failed

PLC_Reconnection : Popup message
PLC_Reconnection: Turn on Leds
PLC_Reconnection -right-> Mobile_Platform_Init : Reconn_success

@enduml
