@startuml rtkcontrol_application

skinparam linetype polyline
skinparam linetype ortho

component rtkcontrol <<GTK application>>

package "GUI" {
    [GTK4] <<Shared library>>
    [Adwaita] <<Shared library>>
    component [com.ronna-medical.rtkcontrol.resource.c] <<Binary resource file>> {
        component [resource] <<GResource XML>>
    }
}
package "Medical Image Processing" {
    [OpenCV] <<Shared library>>
}
package "Ronna toolkit" {
    [rtkcommon] <<Shared library>>
    [rtkcommunication] <<Static library>>
    [rtkalgorithm] <<Static library>>
    [rtksimulation] <<Static library>>
}
package "Logging" {
    [spdlog] <<Shared library>>
}

[GUI] ---> [rtkcontrol]
[Medical Image Processing] ---> [rtkcontrol]
[Logging] ---> [rtkcontrol]
[Ronna toolkit] ---> [rtkcontrol]

@enduml
