@startuml rtkplanning_application

skinparam linetype polyline
skinparam linetype ortho

component rtkplanning <<GTK application>>

package "GUI" {
    [GTK4] <<Shared library>>
    [Adwaita] <<Shared library>>
    component [com.ronna-medical.rtkplanning.resource.c] <<Binary resource file>> {
        component [resource] <<GResource XML>>
    }
}
package "Medical Image Processing, PACS" {
    [DCMTK] <<Shared library>>
    [OpenCV] <<Shared library>>
}
package "Ronna toolkit" {
    [rtkcommon] <<Shared library>>
    [rtkcommunication] <<Static library>>
    [rtkalgorithm] <<Static library>>
}
database "Database" {
    [SQLite] <<Shared library>>
}
package "Math Operations" {
    [Eigen3] <<Shared library>>
}
package "Networking" {
    [libnm] <<Shared library>>
}
package "USB Management" {
    [libusb] <<Shared library>>
}
package "Logging" {
    [spdlog] <<Shared library>>
}

[GUI] ---> [rtkplanning]
[Medical Image Processing, PACS] ---> [rtkplanning]
[Database] -up--> [rtkplanning]
[Math Operations] -up--> [rtkplanning]
[Networking] -up--> [rtkplanning]
[USB Management] -up--> [rtkplanning]
[Logging] -up--> [rtkplanning]
[Ronna toolkit] ---> [rtkplanning]

@enduml
