@startuml IContextViewEvents

package ViewEvents
{

class IContextViewEvents
{
    +OnQuitClicked()
    +OnQuitOk()
    +OnQuitCancel()
    ---
    +OnShowViewerClicked()
    +OnShowInfoClicked()
    ---
    +OnReplanClicked()
    --
    +OnPowerMenuClicked()
    +OnAbortRobotClicked()
    ---
    +OnShutdownConfirmed();
    +OnRestartConfirmed();
    +OnShutdownCanceled();
}

}

@enduml
