@startuml IContextViewEvents

!include ../Events/IBaseEvent.puml

interface IContextViewEvents {
  ==<i><color:DarkBlue>System Control</color></i>==
  + OnContextButtonShutdownClicked()
  + OnContextButtonInformationClicked()
  __
  ==<i><color:DarkBlue>Simulation Controls</color></i>==
  + OnContextButtonSimulationPlayed/Paused/Reset()
  + OnContextRobotSimulationUpdated/Finished()
  + OnContextGhostSimulationUpdated/Finished()
  __
  ==<i><color:DarkBlue>Dropdowns & Selection</color></i>==
  + OnContextDropdownStateSelected(...)
  + OnContextDropdownMarkerSelected(...)
  + OnContextDropdownTrajSelected(...)
  __
  ==<i><color:DarkBlue>Navigation</color></i>==
  + OnContextButtonBackClicked()
  + OnContextButtonNextClicked()
  + OnContextButtonEndOperationClicked()
  __
  <i><color:Gray>Global context view events</color></i>
}

IContextViewEvents -up-|> IBaseEvent

@enduml
