@startuml IDressingViewEvents

!include ../Events/IBaseEvent.puml

interface IDressingViewEvents {
  + OnDressingStartButtonClicked()
  + OnDressingPauseButtonClicked()
  + OnDressingCancelButtonClicked()
  + OnDressingNextButtonClicked()
  + OnDressingBackButtonClicked()
  __
  <i><color:Gray>Robotic dressing view events</color></i>
}

IDressingViewEvents -up-|> IBaseEvent

@enduml
