@startuml IOptimizationViewEvents

!include ../Events/IBaseEvent.puml

interface IOptimizationViewEvents {
  + OnOptimizationSearchButtonClicked()
  + OnOptimizationSolutionSelected(...)
  + OnOptimizationNextButtonClicked()
  + OnOptimizationBackButtonClicked()
  __
  <i><color:Gray>Trajectory optimization view events</color></i>
}

IOptimizationViewEvents -up-|> IBaseEvent

@enduml
