@startuml IPositioningViewEvents

!include ../Events/IBaseEvent.puml

interface IPositioningViewEvents {
  + OnPositioningStartButtonClicked()
  + OnPositioningPauseButtonClicked()
  + OnPositioningCancelButtonClicked()
  + OnPositioningNextButtonClicked()
  + OnPositioningBackButtonClicked()
  __
  <i><color:Gray>Robot positioning view events</color></i>
}

IPositioningViewEvents -up-|> IBaseEvent

@enduml
