@startuml IRegistrationViewEvents

package ViewEvents
{

class IRegistrationViewEvents
{
    +OnAutoRegistration()
    +OnManualRegistration()
    ---
    +OnAcceptManualConfirm()
    +OnResetManualConfirm()
    +OnCancelManualConfirm()
    ---
    +OnAutoRegisterDone()
    +OnAutoRegisterFailed()
    ---
    +OnManualRegisterDone()
    +OnManualRegisterFailed()
}

}

@enduml
