@startuml IRonnaVisionViewEvents

!include ../Events/IBaseEvent.puml

interface IRonnaVisionViewEvents {
  + OnRonnaVisionStartButtonClicked()
  + OnRonnaVisionCaptureButtonClicked()
  + OnRonnaVisionLocalizeButtonClicked()
  + OnRonnaVisionNextButtonClicked()
  + OnRonnaVisionBackButtonClicked()
  __
  <i><color:Gray>RONNA Vision localization view events</color></i>
}

IRonnaVisionViewEvents -up-|> IBaseEvent

@enduml
