@startuml ISimulationViewEvents

!include ../Events/IBaseEvent.puml

interface ISimulationViewEvents {
  + OnSimulationPlayButtonClicked()
  + OnSimulationPauseButtonClicked()
  + OnSimulationResetButtonClicked()
  + OnSimulationNextButtonClicked()
  + OnSimulationBackButtonClicked()
  __
  <i><color:Gray>Trajectory simulation view events</color></i>
}

ISimulationViewEvents -up-|> IBaseEvent

@enduml
