@startuml IStartupViewEvents

!include ../Events/IBaseEvent.puml

interface IStartupViewEvents {
  + OnStartupNextButtonClicked()
  + OnStartupSystemCheckRequired()
  __
  <i><color:Gray>Startup workflow view events</color></i>
}

IStartupViewEvents -up-|> IBaseEvent

@enduml
