@startuml ISystemState_SystemCheck

interface IBaseEvent {
}

package Events {

interface IMobileEvents {
  + OnLoweringCancel()
}

interface IPlcEvents {
  + OnPlcFootswitchPressed()
  + OnPlcFootswitchReleased()
}

interface IRobotEvents {
  + OnRobotPopupSpaceEnsuringOk()
  + OnRobotPopupMasteringStartOk()
  + OnRobotPopupSystemCheckCancelOk()
  + OnRobotMasteringDone(action_code)
  + OnRobotBrakeTestDone(action_code)
  + OnRobotReferencingDone(action_code)
  + OnRobotJMoveToVisionCheckDone(action_code)
  + OnRobotJMoveToDrivingDone(action_code)
}

interface IVisionEvents {
  + OnVisionCoreConnected()
  + OnVisionLocalizationDone(vision_response)
}

}

package ViewEvents {

interface IContextViewEvents {
  + OnContextButtonShutdownClicked()
  + OnContextPopupVisionCheckRetryOk()
  + OnContextPopupVisionCheckCancelOk()
}

interface IStartupViewEvents {
  + OnStartupButtonSystemCheckStarted()
  + OnStartupButtonSystemCheckCanceled()
}

}

interface ISystemState {
  + OnEnter() : void
  + OnExit() : void
  __
  <i><color:Gray>Base state interface</color></i>
  <i><color:Gray>Inherits from relevant event interfaces</color></i>
}

' Show inheritance
IMobileEvents -up-|> IBaseEvent
IPlcEvents -up-|> IBaseEvent
IRobotEvents -up-|> IBaseEvent
IVisionEvents -up-|> IBaseEvent
IContextViewEvents -up-|> IBaseEvent
IStartupViewEvents -up-|> IBaseEvent

ISystemState -up-|> IMobileEvents
ISystemState -up-|> IPlcEvents
ISystemState -up-|> IRobotEvents
ISystemState -up-|> IVisionEvents
ISystemState -up-|> IContextViewEvents
ISystemState -up-|> IStartupViewEvents

@enduml
