@startuml ISystemState_SystemInitializing

interface IBaseEvent {
}

package Events {

interface IAdapterEvents {
  + OnAdapterConnected()
}

interface IMobileEvents {
  + OnMobileConnected()
  + OnEnableReset()
  + OnMobileIdleLowered/Lifted()
  + OnMobilePlatformIdle()
  + OnHomingNeeded/Finished()
  + OnHomingController... (3)
  + OnLiftingController... (3)
  + OnJoystick... (3)
  + OnPoseController... (4)
  + OnEnableWarning()
}

interface IPlannerEvents {
  + OnPlannerConnected()
}

interface IPlcEvents {
  + OnPlcConnected()
  + OnPlcSafetyRunning()
  + OnPlcEStopsRestarted()
  + OnPlcRobotStarted()
  + OnPlcRobotStartFailed(error)
}

interface IPowerEvents {
  + OnPowerConnected()
}

interface IRobotEvents {
  + OnRobotCoreConnected()
  + OnRobotLiveConnected()
}

}

package ViewEvents {

interface IContextViewEvents {
  + OnContextButtonShutdownClicked()
}

}

interface ISystemState {
  + OnEnter() : void
  + OnExit() : void
  __
  <i><color:Gray>Base state interface</color></i>
  <i><color:Gray>Inherits from relevant event interfaces</color></i>
}

' Show inheritance
IAdapterEvents -up-|> IBaseEvent
IMobileEvents -up-|> IBaseEvent
IPlannerEvents -up-|> IBaseEvent
IPlcEvents -up-|> IBaseEvent
IPowerEvents -up-|> IBaseEvent
IRobotEvents -up-|> IBaseEvent
IContextViewEvents -up-|> IBaseEvent

ISystemState -up-|> IAdapterEvents
ISystemState -up-|> IMobileEvents
ISystemState -up-|> IPlannerEvents
ISystemState -up-|> IPlcEvents
ISystemState -up-|> IPowerEvents
ISystemState -up-|> IRobotEvents
ISystemState -up-|> IContextViewEvents

@enduml
