@startuml PlanContext_Ctor

hide footbox
skinparam ParticipantPadding 50

title PlanContext Constructor

participant PlanContext <<rtkplanning>>
participant Viewer <<rtkcommon>>
participant AdvancedImageViewer <<rtkcommon>>
participant VolumeViewer <<rtkcommon>>
participant ImageViewer <<rtkcommon>>

note over PlanContext
    ""m_builder = <color #FF5233>PlanView.ui</color>""

    - get //PlanView.ui// GTK builder objects
    - add widgets for initial window
    - arrange widgets using CSS
end note

PlanContext -[#red]> Adwaita : g_signal_connect( .. )

create Viewer
PlanContext -> Viewer : new( <color #FF5233>viewer.ui,..</color> )
note over Viewer
    ""m_builder = <color #FF5233>viewer.ui</color>""

    - get //viewer.ui// GTK builder objects
    - add widgets for viewer
end note
Viewer -[#red]> Adwaita : g_signal_connect( .. )

loop 3x
    create AdvancedImageViewer
    Viewer -> AdvancedImageViewer : new( )
    note over AdvancedImageViewer : Setup rendering
end

create VolumeViewer
Viewer -> VolumeViewer : new( )
note over VolumeViewer : Setup rendering

create ImageViewer
PlanContext -> ImageViewer : new( )
note over ImageViewer : Setup rendering

PlanContext -> PlanContext : SetState( <color brown>SearchState</color> )

@enduml
