@startmindmap rtkcontrol_with_submodules

+ rtkcontrol

++_ Main
++_ Application
++_ OpContext

++ States
+++_ OpState.cpp
+++_ StartupState.cpp
+++_ PatientStabilizationState.cpp
+++_ OTSRegistrationState.cpp
+++_ OptimalPositioningState.cpp
+++_ PlatformPositioningState.cpp
+++_ InitialSimulationState.cpp
+++_ RonnaVisionState.cpp
+++_ FinalSimulationState.cpp
+++_ TrajectoryTestState.cpp
+++_ DressingState.cpp
+++_ OperationState.cpp

-- rtkalgorithm
--- src
---- Control
-----_ Interpolation
-----_ Kinematics
-----_ Movements
-----_ PyInterface
-----_ Registration
---- Vision
-----_ ImageProcessing
-----_ MarkerEnhancing
-----_ MarkerProcessing
--- scripts
----_ combination_functions
----_ constants_class
----_ kinematics_functions
----_ registration_functions
----_ ransformation_functions
-- rtkcommon
---_ Viewer
---_ ImageViewer
---_ AdvancedImageViewer
---_ ImageInteractorStyle
---_ VolumeViewer
---_ VolumeInteractorStyle
---_ Widget
--- controllers
----_ Controller
----_ MarkerRowController
----_ MarkersController
----_ SplashController
----_ TrajectoriesController
----_ TrajectoryRowController
--- glsl
--- utils
----_ DCMReader2
----_ RtkDropdownObject
--- visualization
---- filters
-----_ rtkGaussianBlurPass
-----_ rtkRenderPass
-----_ rtkSharpenPass
---- overlays
-----_ Crosshair
-----_ Scale
-----_ TextOverlay
----- items
------_ Marker
------_ Trajectory
-- rtkcommunication

--- resources/rom-files
----_ Camera
----_ LeftCollar
----_ RightCollar
----_ Stiffening
----_ Stylus
--- src
---- Server
-----_ HostServer
-----_ HostVisionSession
-----_ ImageVisionSession
-----_ MicroControllerSession
-----_ PlannerSession
-----_ RobotControllerSession
-----_ RobotStatusSession
-----_ Server
-----_ VisionSession
---- Client
-----_ HostClient
-----_ ImageClient
-----_ MobileClient
-----_ MobileStatusClient
-----_ PlannerClient
-----_ VisionClient
---- Common
-----_ CameraManager
-----_ PlcController
-----_ PolarisInterface
-----_ PolarisTool
-----_ Session
-----_ SpatialTransform
-----_ ThreadPool
----- Data
------_ CameraExposure
------_ CameraLeds
------_ CameraSettings
------_ CartesianPose
------_ EulerOrientation
------_ Folder
------_ GuidedTrajectory
------_ MobileRequest
------_ OperationPlan
------_ OptimalSolution
------_ Position
------_ QuatOrientation
------_ ROI
------_ StrayMarker
------_ Trajectory
------_ VisionResponse

-- rtksimulation
--- src
----_ CollisionInterface
----_ MovementPlan
----_ PositioningViewer
----_ SImulationInteractor
----_ SimulationViewer
---- Actors
-----_ AxesAssembly
-----_ BaseActor
-----_ CoverActor
-----_ LinkActor
-----_ PlatformActor
-----_ RobotAssembly
-----_ SimulationActor
-----_ ToolActor
---- Managers
-----_ ComponentsManager
-----_ MockupManager
-----_ MovementPlanManager
-----_ OptimizationManager
-----_ OptimizationWorker
-----_ RegistrationManager
---- Results
-----_ MobilityResults
-----_ MobilityWriter
-----_ PositionResults
-----_ PositionWriter
--- resources/stl-files

@endmindmap
