@startmindmap rtkcommunication

+ rtkcommunication

++ src
+++ Asio
++++_ Clients
++++_ ClientStates
++++_ Encryption
++++_ IOContext
++++_ MockupClients
++++_ MockupServers
++++_ Servers
++++_ ServerStates
++++_ Sockets
++++_ Transfers
+++ Managers
++++_ MobileManager
++++_ PlcManager
++++_ PolarisManager
++++_ UartManager
++++_ UartMockupManager
++++_ UpsManager

++ resources
+++_ certs/ (SSL certificates)

++ docs
+++_ Documentation files

++ tests
+++_ Unit tests

@endmindmap
