@startmindmap rtkcommon

+ rtkcommon

++ src
+++_ Viewer
+++_ ImageViewer
+++_ VolumeViewer
+++_ AdvancedImageViewer
+++_ VolumeRenderer
+++_ Widget

+++ Interactors
++++_ ImageInteractorStyle
++++_ VolumeInteractorStyle

+++ controllers
++++_ Controller

+++ ToolBox
++++_ Protractor
++++_ Ruler
++++_ ToolBox2D
++++_ ToolBox3D

+++ utils
++++_ DicomTagReader

+++ visualization
++++ filters
+++++_ rtkGaussianBlurPass
+++++_ rtkRenderPass
+++++_ rtkSharpenPass
++++ overlays
+++++_ Crosshair
+++++_ Scale
+++++_ TextOverlay
+++++ items
++++++_ Marker
++++++_ Trajectory

+++ Legacy
++++_ Legacy viewer code

++ resources
+++_ GLSL shaders
+++_ resource.xml

++ tests
+++_ Unit tests

@endmindmap
