@startmindmap rtkplanning

+ rtkplanning
++_ main
++ States
+++_ BaseState.cpp
+++_ DatabaseState.cpp
+++_ MarkerState.cpp
+++_ PlansState.cpp
+++_ ReportListState.cpp
+++_ ReportMarkersState.cpp
+++_ ReportPreviewState.cpp
+++_ ReportTrajectoriesState.cpp
+++_ SearchState.cpp
+++_ SyncState.cpp
+++_ TrajectoriesState.cpp
++ ui
+++_ Application
+++_ PlanContext
+++ main
++++_ MainController
++++ database
+++++_ DatabaseController
+++++_ DatabaseModel
++++ media
+++++_ MediaController
++++ pacs
+++++ query
++++++_ PacsQueryController
++++++_ PacsQueryModel
+++++ settings
++++++_ PacsSettingsController
++ database
+++_ Database
+++_ Statemet
+++ model
++++_ Image
++++_ Patient
++++_ Plan
++++_ Report
++++_ Series
++++_ Study
++ helpers
+++_ AppSettings
+++_ DCMReader
+++_ MarkerLocalization
+++_ SearchResViewExt
+++_ SearchResViewLocal
+++_ UsbManager
-- rtkcommon
-- rtkcommunication

@endmindmap
