@startmindmap rtkplanning

+ rtkplanning
++_ Main.cpp
++_ Application.h/cpp
++_ PlanContext.h/cpp

++ Controllers
+++_ CalculationController
+++_ PlannerController
+++_ ViewController

++ ViewControllers
+++_ IViewController
+++_ PlanningViewController

++ States (11)
+++_ DatabaseState
+++_ LoginState
+++_ MarkersState
+++_ PlansState
+++_ ReportListState
+++_ ReportMarkersState
+++_ ReportPreviewState
+++_ ReportTrajectoriesState
+++_ SearchState
+++_ SyncState
+++_ TrajectoriesState

++ DicomManagement
+++_ DicomAnonymizer
+++_ DicomdirParser
+++_ DicomItemExport
+++_ DicomItemSearch
+++_ DicomStoreBase
+++_ DicomStoreExport
+++_ DicomStoreManager
+++_ DicomStoreSearch
+++_ DicomTagPreparator

++ PacsManagement
+++_ PacsClient
+++_ PacsConfigFileManager

++ SettingsManagement
+++_ Settings classes

++ MarkerProcessing
+++_ Marker processing logic

++ UsbManagement
+++_ USB device handling

++ SystemErrors
+++_ Error handling

++ Events
+++_ Event interfaces

++ ViewEvents
+++_ View event interfaces

-- resources
---_ icons/
---_ images/
---_ styles/
---_ views/

-- external (submodules)
--- rtkdata
--- rtkelements
--- rtkalgorithm
--- rtkcommon
--- rtkcommunication
--- system-manifest

@endmindmap
