@startmindmap rtksimulation

+ rtksimulation

++ src
+++_ Structures

+++ Actors
++++_ ActorFactory
++++_ AxesActor
++++_ BaseActor
++++_ CoverActor
++++_ LinkActor
++++_ PlatformActor
++++_ RobotAssembly
++++_ SimulationActor
++++_ ToolActor

+++ Managers
++++_ MockupManager
++++_ MovementGuide
++++_ MovementManager
++++_ MovementSubManager
++++_ MovementWorker
++++_ OffsettingGuide
++++_ OptimizationManager
++++_ OptimizationWorker
++++_ ParametersChooser
++++_ RegistrationManager

+++ Simulation
++++_ CollisionInterface
++++_ CollisionPair
++++_ MousePosition
++++_ PoseAssembler
++++_ SegmentAssembler
++++_ SimulationInteractor
++++_ SimulationScene
++++_ SimulationViewer
++++_ SimulationWidget

+++ Results
++++_ MobilityResults
++++_ MobilityWriter
++++_ PositionResults
++++_ PositionWriter

++ resources
+++_ stl-files/ (3D models)

++ docs
+++_ Documentation files

++ tests
+++_ Unit tests

@endmindmap
