@startuml IMobileEvents

class IMobileEvents
{
    +OnMobileInitialized();
    ---
    +OnHomingNeeded();
    ---
    +OnLift();
    +OnLower();
    +OnStartJoystick();
    +OnStartJoystickRotation();
    +OnStartJoystickTranslation();
    ---
    +OnMobileCommandClientConnectionError();
    +OnMobileStateClientConnectionError();
    ---
    +OnMobileControllerError();
}

@enduml
