@startuml

class IPlanningStationEvents
{
    +OnStationConnected()
    +OnStationDisconnected()
    +OnSendPlanRequested()
    +OnPlanSent()
    +OnReplanRequested()
    +OnPlanAccepted()
    +OnPlanRejected()
    ---
    +OnConfirmRequest()
    +OnReceiveUpdate()
    +OnReceiveComplete()
}

@enduml
