@startuml

class IRobotEvents
{
    +OnRobotConnected()
    +OnRobotDisconnected()
    +OnStandStillViolation()
    +OnRobotReject()
    +OnRobotDemastered()
    ---
    +OnRobotStatusEvent()
    +OnTransportPoseReached()
}

@enduml
