@startuml UnregisteredState

!include ../../ISystemState.puml
!include ../Events/IPolarisEvents.puml
!include ../../ViewEvents/IRegistrationViewEvents.puml
!include ../../ViewEvents/IStateControlViewEvents.puml
!include ../../ViewEvents/IContextViewEvents.puml

!include ../../OpContext.puml

!include ../../ViewController/ContextViewController.puml
!include ../../ViewController/StateControlViewController.puml
!include ../../ViewController/RegistrationViewController.puml

!include ../Controllers/PolarisController.puml

package RegisteredStates
{

class UnregisteredState
{
    -OverallPolarisTools _overall_ots_tools
    +OnEnter()
    +OnExit()
    #OnBackButtonClicked()
    #OnPolarisDataUpdated()
    #OnAutoRegistration()
    #OnManualRegistration()
    #OnAutoRegisterDone()
    #OnAutoRegisterFailed()
}

class RegisteredState
{
    -OverallPolarisTools _overall_ots_tools
    +OnEnter()
    +OnExit()
    #OnBackButtonClicked()
    #OnNextButtonClicked()
    #OnPolarisDataUpdated()
    #OnAutoRegistration()
    #OnManualRegistration()
    #OnAutoRegisterDone()
    #OnAutoRegisterFailed()
}

class ManualRegisteringState
{
    -OverallPolarisTools _overall_ots_tools
    -std::vector<Position> _P_markers_points
    -int _selected_CT_marker_i
    +OnEnter()
    +OnExit()
    #OnBackButtonClicked()
    #OnPolarisDataUpdated()
    #OnAcceptManualConfirm()
    #OnResetManualConfirm()
    #OnCancelManualConfirm()
    #OnManualRegisterDone()
    #OnManualRegisterFailed()
}

}

ISystemState --up|> IPolarisEvents : is
ISystemState --up|> IRegistrationViewEvents : is
ISystemState --up|> IStateControlViewEvents : is
ISystemState --up|> IContextViewEvents : is
UnregisteredState --up|> ISystemState : is

UnregisteredState .right.> OpContext : uses

OpContext o-down- ContextViewController : has
OpContext o-down- StateControlViewController : has
OpContext o-down- RegistrationViewController : has
OpContext o-right- PolarisController : has
OpContext o-left- ISystemState : has

OpContext <.down. ContextViewController : uses
OpContext <.down. StateControlViewController : uses
OpContext <.down. RegistrationViewController : uses
OpContext <.right. PolarisController : uses

@enduml
