@startuml Application_and_States

class GTK << (L, orchid) external library>>
class AdwApplication << (L, orchid) external library>>
' class libusb << (L, orchid) external library>>
' class vtk << (L, orchid) external library>>
' class itk << (L, orchid) external library>>
' class dcmtk << (L, orchid) external library>>
' class sqlite3 << (L, orchid) external library>>
' class eigen << (L, orchid) external library>>
' class "Boost::json" << (L, orchid) external library>>

class Application
class Controller
class PlanContext
interface BaseState
class LoginState << (S,#FF7700) Singleton >>
class SearchState << (S,#FF7700) Singleton >>
class DatabaseState << (S,#FF7700) Singleton >>
class PlansState << (S,#FF7700) Singleton >>
class MarkersState << (S,#FF7700) Singleton >>
class TrajectoriesState << (S,#FF7700) Singleton >>
class SyncState << (S,#FF7700) Singleton >>
class ReportListState << (S,#FF7700) Singleton >>
class ReportPreviewState << (S,#FF7700) Singleton >>
class ReportMarkerState << (S,#FF7700) Singleton >>
class ReportTrajectoriesState << (S,#FF7700) Singleton >>

Application .up.> GTK : uses >
Application o-up- AdwApplication : uses >
Application o-down- PlanContext : uses >
PlanContext -up-|> Controller : is >
PlanContext o-left- BaseState : uses >
LoginState -right-|> BaseState : is >
SearchState -up-|> BaseState : is >
DatabaseState -up-|> BaseState : is >
PlansState -up-|> BaseState : is >
MarkersState -up-|> BaseState : is >
TrajectoriesState -up-|> BaseState : is >
SyncState -up-|> BaseState : is >

ReportListState --down-|> BaseState : is >
ReportPreviewState --down-|> BaseState : is >
ReportMarkerState --down-|> BaseState : is >
ReportTrajectoriesState --down-|> BaseState : is >

' SearchState .down.> libusb : uses >
' DatabaseState .down.> libusb : uses >
' DatabaseState .down.> vtk : uses >
' DatabaseState .down.> itk : uses >
' DatabaseState .down.> dcmtk : uses >
' DatabaseState .down.> sqlite3 : uses >
' PlansState .down.> eigen : uses >
' PlansState .down.> "Boost::json" : uses >
' PlansState .down.> itk : uses >

@enduml
