@startuml SearchState

class GTK << (L, orchid) external library>>
class AdwApplication << (L, orchid) external library>>
class Application
class Controller
class PlanContext
interface BaseState
class SearchState << (S,#FF7700) Singleton >>
class libusb << (L, orchid) external library>>

Application o-up- AdwApplication : uses >
Application o-up- GTK : uses >
Application o-- PlanContext : uses >
PlanContext -up-|> Controller : is >
PlanContext o-left- BaseState : uses >
SearchState -up-|> BaseState : is >
SearchState ..> libusb : uses >

@enduml
