@startuml IAdapterEvents

!include IBaseEvent.puml

interface IAdapterEvents {
  + OnAdapterConnected()
  + OnAdapterDisconnected()
  + OnAdapterConnectionError(error)
  __
  <i><color:Gray>Robotic adapter communication events</color></i>
}

IAdapterEvents -up-|> IBaseEvent

@enduml
