@startuml IPlcEvents

!include IBaseEvent.puml

interface IPlcEvents {
  ==<i><color:DarkBlue>Connection</color></i>==
  + OnPlcConnected()
  + OnPlcConnectionError(error)
  __
  ==<i><color:DarkBlue>E-Stop Events</color></i>==
  + OnPlcRobotEStopPressed/Released()
  + OnPlcJoystickEStopPressed/Released()
  + OnPlcEStopsRestarted/RestartFailed()
  __
  ==<i><color:DarkBlue>Footswitch Events</color></i>==
  + OnPlcFootswitchPressed/Released()
  + OnPlcFootswitchRestarted/RestartFailed()
  __
  ==<i><color:DarkBlue>Tool Events</color></i>==
  + OnPlcToolMounted/Unmounted()
  + OnPlcToolRestarted/RestartFailed()
  __
  ==<i><color:DarkBlue>Safety Events (8 states)</color></i>==
  + OnPlcSafetyRunning/Stopped/Error/Reset()
  + OnPlcSafetyStarting/StopError/...()
  __
  ==<i><color:DarkBlue>Error Detection</color></i>==
  + OnPlcRobotCollisionDetected()
  + OnPlcStandstillViolated()
  + OnPlcTemperatureViolated()
  + OnPlcStationErrorDetected()
}

IPlcEvents -up-|> IBaseEvent

@enduml
