@startuml IVisionEvents

!include IBaseEvent.puml

interface IVisionEvents {
  ==<i><color:DarkBlue>Connection</color></i>==
  + OnVisionConnected/Disconnected()
  + OnVisionConnectionError(error)
  __
  ==<i><color:DarkBlue>Image Capture</color></i>==
  + OnVisionImageCaptured(...)
  + OnVisionImageError(...)
  __
  ==<i><color:DarkBlue>Localization</color></i>==
  + OnVisionLocalizationDone(...)
  + OnVisionLocalizationFailed(...)
  __
  <i><color:Gray>Camera and vision system events</color></i>
}

IVisionEvents -up-|> IBaseEvent

@enduml
