@startuml ISystemState

!include Events/IPlcEvents.puml
!include Events/IRobotEvents.puml
!include ViewEvents/IContextViewEvents.puml
!include ViewEvents/IStartupViewEvents.puml

interface ISystemState
{
    +OnEnter(OpContext) = 0
    +OnExit(OpContext) = 0
    +OnUpdate(OpContext)
}

ISystemState --up|> IContextViewEvents
ISystemState --up|> IStartupViewEvents
ISystemState --up|> IPlcEvents
ISystemState --up|> IRobotEvents

@enduml
