@startuml OpContext

!include Controllers/PlcController.puml
!include ViewControllers/ContextViewController.puml
!include ViewControllers/StartupViewController.puml

class OpContext
{
	-_active_vc : IViewController
	---
	+SetSystemState(ISystemState) : void
	+GetSystemState() : ISystemState

	+SetupControllersAndStartWorkflow() : void
	+SetViewController(IViewController) : void
}

OpContext -left-> ISystemState : _active_state
OpContext --> StartupViewController : startup_vc
OpContext --> ContextViewController : context_vc
OpContext -right-> PlcController : plc_controller

@enduml
