@startuml ContextViewController

class ContextViewController {
  + Activate() : void
  + Deactivate() : void
  + pc_shutdown_action : ActionPopup
  __
  <i><color:Gray>Global context view</color></i>
  <i><color:Gray>Handles shutdown and system controls</color></i>
}

@enduml
