@startuml StartupViewController

class StartupViewController {
  + Activate() : void
  + Deactivate() : void
  + pc_initializing : PopupControl
  __
  <i><color:Gray>Startup workflow view</color></i>
}

@enduml
