@startuml

actor User

activate OpContext
OpContext -> OpContext : Set Startup State
OpContext -> Polaris : Connect to Polaris
OpContext -> PLC : Connect to PLC
OpContext -> OpContext : Initialize operatio plan
OpContext -> MobileClient : Connect to Mobile Client
OpContext -> MobileStatusClient : Connect to Mobile Status Client
deactivate OpContext

PLC -> OpContext : PLC Connected
activate OpContext
OpContext -> PLC : Initialize PLC
OpContext -> PLC : Disable Standstill Monitoring
deactivate OpContext

MobileClient -> OpState : Mobile Client Connected
note over OpState 
    Connected event does 
    not affect the state.
end note

MobileStatusClient -> OpState : Mobile Status Client Connected
note over OpState 
    Initializing popups.
    Connected event does 
    not affect the state.
end note

MobileStatusClient -> OpState : Received Mobile Status Response
activate OpState
OpState --> OpContext : Set Mobile State and Arm Toggle Transport
deactivate OpState

PLC -> OpContext : Received PLC Status PLC_SAFETY_DEACTIVE
activate OpContext
note over OpContext : Wait for 15 Seconds
OpContext -> PLC : Start Safety Controller
deactivate OpContext

PLC -> OpContext : Received PLC Status PLC_SAFETY_RUN
activate OpContext
note over OpContext : Wait for 1 Second
OpContext -> PLC : Initialize Emergency Stop
deactivate OpContext

activate StartupState
StartupState -> StartupState : Start Loading Function
note over StartupState
Show Loading Screen
and Check Conditions
in a loop.
end note

StartupState --> OpContext : Is robot initialized and mobile state not PLC_NOT_CONNECTED
OpContext --> StartupState : Yes

StartupState -> StartupState : Initialize server sessions

note over StartupState
    Set Reject callback for RC.
    Set callback on robot status.
    Set receive operation plan.
end note

note over StartupState
    If tool is mounted use
    micro controller session
    to read EEPROM data.
    There is no check if the
    connection was established.
end note

MicroController -> StartupState : Connect to server
StartupState -> PLC : Check if tool is mounted
PLC -> StartupState : Tool is mounted
StartupState -> MicroController : Read EEPROM data
deactivate StartupState
activate MicroController
MicroController -> OpContext : Received EEPROM data
deactivate MicroController
activate OpContext
OpContext -> PLC : Set Active Tool

OpContext -> User : Ask user to restart tool
User -> OpContext : Confirm restart tool
note over OpContext : User cannot decline tool restart.

OpContext -> OpContext : Check if tool is commissioned.

OpContext -> PLC : Restart Tool
deactivate OpContext

RobotStatusController -> OpContext : Connected to server
RobotStatusController -> OpContext : Received robot status

note over OpContext
    Update active target.
    Check if robot is mastered.
    Check if systemcheck is needed.
end note

MobileStatusClient -> OpState : Received Mobile Status Response.
activate OpState
OpState --> OpContext : Mobile state is HOMING_NEEDED.
OpState -> User : Popup: Ask user to start homing.
User -> OpState : Confirm homing.
OpState -> MobileClient : Start Homing.
OpState -> OpState : Start monitoring homing.
activate OpState
OpState -> OpState : Wait for IDLE_LOWERED.
deactivate OpState

OpState -> PLC : Check referencing.
OpState -> User : Popup: Ask user to start system check.
deactivate OpState

User -> OpState : Start System Check.
activate OpState
OpState -> StartupState : Start System Check.
deactivate OpState

Activate StartupState
StartupState -> OpContext : Check if mobile platform is lowered.
StartupState -> PLC : Enable System Check.
StartupState -> OpContext : Check if robot is initialized.

StartupState -> User : Popup: Ask user to ensure enough space.
User -> StartupState : Confirm enough space.
StartupState -> User : Popup: Ask user to mount the camera tool.
User -> StartupState : Confirm camera tool mounted.
StartupState -> StartupState : Is Camera Tool Mounted?
note over StartupState
    If camera tool is not mounted
    ask user again to mount camera.
end note

StartupState -> User : Popup: Ask user to connect the footswitch.
User -> StartupState : Confirm footswitch connected.
StartupState -> RobotController : Start System Check
deactivate StartupState
activate RobotController
note right of RobotController
    During Szstem check
    EStop shall be released.
    Footswitch shall be pressed.
end note
RobotController -> StartupState : System check initialized.
deactivate RobotController
activate StartupState
StartupState -> RobotController : Start braketest.
deactivate StartupState
activate RobotController
RobotController -> StartupState : Braketest done.
deactivate RobotController
activate StartupState
StartupState -> RobotController : Start referencing.
deactivate StartupState
activate RobotController
RobotController -> StartupState : Referencing done.
deactivate RobotController
activate StartupState
StartupState -> RobotController : Start Vision Check.
deactivate StartupState
activate RobotController
RobotController -> StartupState : Vision Check done.
deactivate RobotController
activate StartupState

StartupState -> Vision : Automatically Find Marker.
deactivate StartupState
activate Vision
Vision -> OpContext : Found Marker.
deactivate Vision

activate OpContext
note over OpContext : Check calculated distance.
OpContext -> RobotController : End System Check.
deactivate OpContext

activate PlanningStation
note over PlanningStation : User defines operation plan.
PlanningStation -> StartupState : Send plan request.

activate StartupState
StartupState -> User : Popup: Ask user to accept operation plan.
User -> StartupState : Accept operation plan.
StartupState -> PlanningStation : Confirm operation plan.
PlanningStation -> StartupState : Downloading operation plan and DICOM images.
PlanningStation -> StartupState : Plan receiving update. Update progress bar.
PlanningStation -> StartupState : Operation plan received.
deactivate PlanningStation

note over StartupState
    Check if the tool is mounted.
    If zes read the data from EEPROM.
end note

StartupState -> PLC : Check Referencing.

note over StartupState
    If referencing is OK.
end note

StartupState -> OpContext : Set <b>Patient Stabilization State

@enduml